###
GET http://192.168.8.149:8080/modbus/read-all
Accept: application/json

###
GET http://192.168.8.149:8080/modbus/read-register0
Accept: application/json

###
GET http://192.168.8.149:8080/modbus/read-register1
Accept: application/json

###
POST http://192.168.8.149:8080/modbus/write-register0
Content-Type: application/json

{"valueFloat": 45.1}

###

###
POST http://192.168.8.149:8080/modbus/write-register1
Content-Type: application/json

{"valueFloat": 63.7}

###